repository: vmware.github.io/docker-volume-vsphere

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: vSphere Docker Volume Service
# this appears on the top navigation bar next to the home button

site_title: vSphere Docker Volume Service
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: VMWare
# this appears in the footer

github_editme_path: vmware/docker-volume-vsphere/edit/master/docs/external
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus_shortname: idrbwjekyll
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
# these are the files and directories that jekyll will exclude from the build

feedback_subject_line: vSphere Docker Volume Service

feedback_email: contact@vmware.com
# used as a contact email for the Feedback link in the top navigation bar

feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

sidebars:
- home_sidebar

